name: ExoMarketPlugin
description: A plugin for managing the market GUI
depend: [Essentials]
version: 1.5.8
api-version: 1.21
main: com.exomarket.ExoMarketPlugin

commands:
  market:
    description: Open the market GUI
    usage: /market
  sellhand:
    description: Sell the item in your hand
    usage: /sellhand
  marketreload:
    description: Reload the plugin
    usage: /marketreload
  autosell:
    description: Configure automatic selling of items
    usage: /autosell

default-config:
  MarketManager:
    MarketValueMultipier: 6
    MaxPricePercent: 5
    MinPrice: 0.01