name: StarhavenSMPCore
description: A plugin for managing the market GUI
depend: [Essentials]
softdepend: [PlaceholderAPI, BetterTeams]
version: 4.6.42
api-version: 1.21
main: com.starhavensmpcore.core.StarhavenSMPCore

commands:
  market:
    description: Open the market GUI
    usage: /market
  sellhand:
    description: Sell the item in your hand
    usage: /sellhand
  marketreload:
    description: Reload the plugin
    usage: /marketreload
  autosell:
    description: Configure automatic selling of items
    usage: /autosell
  starhavengive:
    description: Give Starhaven custom items
    usage: /starhavengive <player> <starhaven:item> [amount]

default-config:
  MarketManager:
    MarketValueMultipier: 6
    MaxPricePercent: 5
    MinPrice: 0.01
