name: StarhavenSMPCore
description: A plugin for managing the market GUI
depend: [Essentials]
softdepend: [PlaceholderAPI, BetterTeams]
version: 4.7.17
api-version: 1.21
main: com.starhavensmpcore.core.StarhavenSMPCore

commands:
  market:
    description: Open the market GUI
    usage: /market
  sellhand:
    description: Sell the item in your hand
    usage: /sellhand
  marketreload:
    description: Reload the plugin
    usage: /marketreload
  autosell:
    description: Configure automatic selling of items
    usage: /autosell
  ore:
    description: Ore generation repair tools
    usage: /ore repair <custom_ore>
  starhavengive:
    description: Give Starhaven custom items
    usage: /starhavengive <player> <starhaven:item> [amount]
  new:
    description: Add a what's new announcement
    usage: /new <message>
  help:
    description: Open the help menu
    usage: /help

permissions:
  Starhaven.Admin:
    description: Allows adding what's new announcements
    default: op

default-config:
  MarketManager:
    MarketValueMultipier: 6
    MaxPricePercent: 5
    MinPrice: 0.01
