name: Bug report
description: Report a problem or regression
title: "[Bug]: "
labels:
  - bug
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide exact steps so we can reproduce the issue.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Plugin version
      placeholder: e.g. 4.6.10
    validations:
      required: true
  - type: input
    id: server
    attributes:
      label: Server type & version
      placeholder: e.g. Paper 1.21.11
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack trace
      description: Paste relevant logs (redact sensitive info).
      render: text
  - type: textarea
    id: config
    attributes:
      label: Config changes
      description: Relevant config or settings.
