name: Exploit report
description: Report a security issue or exploit privately
title: "[Exploit]: "
labels:
  - security
body:
  - type: markdown
    attributes:
      value: |
        **Please avoid posting sensitive details publicly.**
        If this is critical, open the issue with minimal info and contact the maintainer privately.
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Brief description of the exploit.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: What can be gained or compromised?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps (redacted)
      description: Provide high-level steps without sensitive details.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Plugin version
      placeholder: e.g. 4.6.10
    validations:
      required: true
  - type: input
    id: server
    attributes:
      label: Server type & version
      placeholder: e.g. Paper 1.21.11
    validations:
      required: true
  - type: textarea
    id: mitigation
    attributes:
      label: Suggested mitigation
      description: Any temporary workarounds or fixes.
